// packages/kit/src/react/field.tsx
import { FC, memo, useLayoutEffect, useRef } from 'react';
import { noop } from '../utils.js';
import { cloneFieldNode } from '../vanilla/field.js';

export interface AnkiFieldProps {
  name: string;
  className?: string;
}
export const AnkiField: FC<AnkiFieldProps> = memo(({ name, className }) => {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const cloned = cloneFieldNode(name);
    if (!ref.current || !cloned) {
      return noop;
    }

    ref.current.appendChild(cloned);
    return () => ref.current?.removeChild(cloned);
  }, [name]);

  return <div ref={ref} className={`ae-field-container ${className || ''}`} />;
});

// packages/kit/src/vue/field.vue
<template>
  <div ref="containerRef" :class="`ae-field-container ${className || ''}`" />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { cloneFieldNode } from '../vanilla/field.js';
import type { Ref } from 'vue';

interface Props {
  name: string;
  className?: string;
}

const props = defineProps<Props>();
const containerRef: Ref<HTMLDivElement | null> = ref(null);
let clonedNode: Node | null = null;

const updateField = () => {
  if (!containerRef.value) return;

  if (clonedNode) {
    containerRef.value.removeChild(clonedNode);
    clonedNode = null;
  }

  const cloned = cloneFieldNode(props.name);
  if (cloned) {
    containerRef.value.appendChild(cloned);
    clonedNode = cloned;
  }
};

onMounted(updateField);
watch(() => props.name, updateField);

onUnmounted(() => {
  if (clonedNode && containerRef.value) {
    containerRef.value.removeChild(clonedNode);
  }
});
</script>
